-- Original local-development problems. Author and license are recorded per product policy.
WITH seeds (slug, title, difficulty, entrypoint, statement_markdown, starter_code, reference_solution, tests) AS (
  VALUES
    ('digit-sum','Digit Sum','easy','digit_sum','Return the sum of a non-negative integer''s decimal digits.',E'def digit_sum(number):\n    pass\n',E'def digit_sum(number):\n    return sum(map(int, str(number)))\n','[{"input":"{\"args\":[123]}","output":"6","public":true},{"input":"{\"args\":[0]}","output":"0","public":true},{"input":"{\"args\":[999]}","output":"27","public":false}]'::jsonb),
    ('unique-sorted','Unique Sorted Values','easy','unique_sorted','Return unique integer values in ascending order.',E'def unique_sorted(values):\n    pass\n',E'def unique_sorted(values):\n    return sorted(set(values))\n','[{"input":"{\"args\":[[3,1,3,2]]}","output":"[1,2,3]","public":true},{"input":"{\"args\":[[]]}","output":"[]","public":true},{"input":"{\"args\":[[-1,-1,0]]}","output":"[-1,0]","public":false}]'::jsonb),
    ('word-count','Word Count','easy','word_count','Count whitespace-separated words.',E'def word_count(text):\n    pass\n',E'def word_count(text):\n    return len(text.split())\n','[{"input":"{\"args\":[\"hello world\"]}","output":"2","public":true},{"input":"{\"args\":[\"\"]}","output":"0","public":true},{"input":"{\"args\":[\"  a  b  \"]}","output":"2","public":false}]'::jsonb),
    ('toggle-case','Toggle Case','easy','toggle_case','Swap the case of every letter.',E'def toggle_case(text):\n    pass\n',E'def toggle_case(text):\n    return text.swapcase()\n','[{"input":"{\"args\":[\"AbC\"]}","output":"\"aBc\"","public":true},{"input":"{\"args\":[\"123\"]}","output":"\"123\"","public":true},{"input":"{\"args\":[\"CodeDuel\"]}","output":"\"cODEdUEL\"","public":false}]'::jsonb),
    ('running-total','Running Total','easy','running_total','Return cumulative sums.',E'def running_total(values):\n    pass\n',E'def running_total(values):\n    total = 0\n    result = []\n    for value in values:\n        total += value\n        result.append(total)\n    return result\n','[{"input":"{\"args\":[[2,3,-1]]}","output":"[2,5,4]","public":true},{"input":"{\"args\":[[]]}","output":"[]","public":true},{"input":"{\"args\":[[-2,2]]}","output":"[-2,0]","public":false}]'::jsonb),
    ('clamp-value','Clamp Value','easy','clamp_value','Limit a value to inclusive lower and upper bounds.',E'def clamp_value(value, lower, upper):\n    pass\n',E'def clamp_value(value, lower, upper):\n    return max(lower, min(value, upper))\n','[{"input":"{\"args\":[7,0,5]}","output":"5","public":true},{"input":"{\"args\":[-2,0,5]}","output":"0","public":true},{"input":"{\"args\":[3,0,5]}","output":"3","public":false}]'::jsonb),
    ('pair-indices','Pair Indices','medium','pair_indices','Return indices of two values whose sum is target.',E'def pair_indices(numbers, target):\n    pass\n',E'def pair_indices(numbers, target):\n    seen = {}\n    for index, value in enumerate(numbers):\n        if target - value in seen:\n            return [seen[target - value], index]\n        seen[value] = index\n    return []\n','[{"input":"{\"args\":[[2,7,11,15],9]}","output":"[0,1]","public":true},{"input":"{\"args\":[[3,3],6]}","output":"[0,1]","public":true},{"input":"{\"args\":[[-1,-2,-3,-4],-7]}","output":"[2,3]","public":false}]'::jsonb),
    ('balanced-brackets','Balanced Brackets','medium','is_balanced','Return whether parentheses are balanced.',E'def is_balanced(text):\n    pass\n',E'def is_balanced(text):\n    depth = 0\n    for char in text:\n        if char == \"(\": depth += 1\n        elif char == \")\":\n            depth -= 1\n            if depth < 0: return False\n    return depth == 0\n','[{"input":"{\"args\":[\"(())\"]}","output":"true","public":true},{"input":"{\"args\":[\"(()\"]}","output":"false","public":true},{"input":"{\"args\":[\")(\"]}","output":"false","public":false}]'::jsonb),
    ('rotate-right','Rotate Right','medium','rotate_right','Rotate a list right by a number of steps.',E'def rotate_right(values, steps):\n    pass\n',E'def rotate_right(values, steps):\n    if not values: return []\n    steps %= len(values)\n    return values[-steps:] + values[:-steps] if steps else values\n','[{"input":"{\"args\":[[1,2,3,4],1]}","output":"[4,1,2,3]","public":true},{"input":"{\"args\":[[1,2,3],4]}","output":"[3,1,2]","public":true},{"input":"{\"args\":[[],5]}","output":"[]","public":false}]'::jsonb),
    ('merge-ranges','Merge Ranges','medium','merge_ranges','Merge overlapping sorted closed ranges.',E'def merge_ranges(ranges):\n    pass\n',E'def merge_ranges(ranges):\n    result = []\n    for start, end in ranges:\n        if not result or start > result[-1][1]: result.append([start, end])\n        else: result[-1][1] = max(result[-1][1], end)\n    return result\n','[{"input":"{\"args\":[[[1,3],[2,5],[8,9]]]}","output":"[[1,5],[8,9]]","public":true},{"input":"{\"args\":[[]]}","output":"[]","public":true},{"input":"{\"args\":[[[1,2],[3,4]]]}","output":"[[1,2],[3,4]]","public":false}]'::jsonb),
    ('top-frequency','Top Frequency','medium','top_frequency','Return the most frequent value; break ties by smaller value.',E'def top_frequency(values):\n    pass\n',E'def top_frequency(values):\n    counts = {}\n    for value in values: counts[value] = counts.get(value, 0) + 1\n    return min(counts, key=lambda value: (-counts[value], value))\n','[{"input":"{\"args\":[[2,1,2,3,3,3]]}","output":"3","public":true},{"input":"{\"args\":[[4,1,4,1]]}","output":"1","public":true},{"input":"{\"args\":[[-1,-1,0]]}","output":"-1","public":false}]'::jsonb),
    ('longest-run','Longest Run','medium','longest_run','Return the longest consecutive run of equal values.',E'def longest_run(values):\n    pass\n',E'def longest_run(values):\n    best = current = 0\n    previous = object()\n    for value in values:\n        current = current + 1 if value == previous else 1\n        best = max(best, current)\n        previous = value\n    return best\n','[{"input":"{\"args\":[[1,1,2,2,2,3]]}","output":"3","public":true},{"input":"{\"args\":[[]]}","output":"0","public":true},{"input":"{\"args\":[[5,5,5,5]]}","output":"4","public":false}]'::jsonb),
    ('minimum-coins','Minimum Coins','advanced','minimum_coins','Return fewest coins required for amount, or -1.',E'def minimum_coins(coins, amount):\n    pass\n',E'def minimum_coins(coins, amount):\n    best = [0] + [amount + 1] * amount\n    for total in range(1, amount + 1):\n        for coin in coins:\n            if coin <= total: best[total] = min(best[total], best[total - coin] + 1)\n    return best[amount] if best[amount] <= amount else -1\n','[{"input":"{\"args\":[[1,3,4],6]}","output":"2","public":true},{"input":"{\"args\":[[2],3]}","output":"-1","public":true},{"input":"{\"args\":[[5,7],0]}","output":"0","public":false}]'::jsonb),
    ('grid-shortest-path','Grid Shortest Path','advanced','shortest_path','Return shortest four-direction path through zero cells, or -1.',E'def shortest_path(grid):\n    pass\n',E'def shortest_path(grid):\n    from collections import deque\n    if not grid or grid[0][0] or grid[-1][-1]: return -1\n    queue, seen = deque([(0,0,0)]), {(0,0)}\n    while queue:\n        row, col, distance = queue.popleft()\n        if (row, col) == (len(grid)-1, len(grid[0])-1): return distance\n        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr, nc = row + dr, col + dc\n            if 0 <= nr < len(grid) and 0 <= nc < len(grid[0]) and not grid[nr][nc] and (nr,nc) not in seen:\n                seen.add((nr,nc)); queue.append((nr,nc,distance+1))\n    return -1\n','[{"input":"{\"args\":[[[0,0],[1,0]]]}","output":"2","public":true},{"input":"{\"args\":[[[0,1],[1,0]]]}","output":"-1","public":true},{"input":"{\"args\":[[[0]]]}","output":"0","public":false}]'::jsonb)
), inserted AS (
  INSERT INTO problems (id, slug, title, difficulty, format, entrypoint, statement_markdown, starter_code, reference_solution, time_limit_ms, memory_limit_mb, author_name, content_license, published_at)
  SELECT gen_random_uuid(), slug, title, difficulty::difficulty, 'function', entrypoint, statement_markdown, starter_code, reference_solution, 2000, 128, 'CodeDuel Team', 'original', now()
  FROM seeds ON CONFLICT (slug) DO NOTHING RETURNING id, slug
)
INSERT INTO problem_tests (id, problem_id, input_data, expected_output, is_public, weight, ordinal)
SELECT gen_random_uuid(), inserted.id, test.value->>'input', test.value->>'output', (test.value->>'public')::boolean, 1, test.ordinal
FROM inserted JOIN seeds USING (slug)
CROSS JOIN LATERAL jsonb_array_elements(seeds.tests) WITH ORDINALITY AS test(value, ordinal);
