import Link from "next/link";

const ranks = [
  ["Easy", "Gold II", "32–18"],
  ["Medium", "Silver I", "18–14"],
  ["Advanced", "Placements", "3 / 5 complete"],
];

export default function PlayerProfilePage() {
  return <main className="min-h-screen bg-[#f7f7f5] px-5 py-10 text-[#161616] sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/" className="text-xl font-bold tracking-[-0.06em]">CodeWars<span className="text-[#ed5b39]">.</span></Link><section className="mt-10 rounded-2xl border border-black/10 bg-white p-7 sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-5"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#a26b19] text-xl font-bold text-white">KI</span><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#ed5b39]">Player profile</p><h1 className="mt-1 text-4xl font-semibold tracking-[-0.055em]">KiteByte</h1><p className="mt-1 text-sm text-black/55">Playing Python · Joined Season Zero</p></div></div><button className="self-start rounded-lg border border-black/15 px-4 py-2.5 text-sm font-bold hover:border-black">Report player</button></div><div className="mt-9 grid gap-px overflow-hidden rounded-xl border border-black/10 bg-black/10 sm:grid-cols-3">{ranks.map(([difficulty, rank, record]) => <div key={difficulty} className="bg-[#f9f9f7] p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-black/45">{difficulty}</p><p className="mt-2 text-xl font-semibold">{rank}</p><p className="mt-1 text-sm text-black/55">{record}</p></div>)}</div><section className="mt-10"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recent ranked matches</h2><span className="text-sm text-black/45">Last 10 shown</span></div><div className="mt-4 divide-y divide-black/10 rounded-xl border border-black/10"><div className="flex items-center justify-between p-4 text-sm"><div><b>vs You</b><span className="text-black/50"> · Medium</span></div><div className="text-right"><b className="text-[#c73d25]">Loss · 1–2</b><p className="mt-1 text-xs text-black/45">Just now</p></div></div><div className="flex items-center justify-between p-4 text-sm"><div><b>vs LogicLoop</b><span className="text-black/50"> · Easy</span></div><div className="text-right"><b className="text-[#21885d]">Win · 2–0</b><p className="mt-1 text-xs text-black/45">2 hours ago</p></div></div></div></section></section></div></main>;
}
