"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell,buttonClass,ErrorNotice } from "@/components/app-shell";
import { api } from "@/lib/api-client";
import { useResource } from "@/lib/hooks/use-resource";
import { difficultyLabel,rankLabel } from "@/lib/match-view";
import type { Difficulty } from "@/types/api";
export default function Queue(){
  const router=useRouter();const {data:queue,error,refresh}=useResource("queue",api.getQueue,3000);
  const {data:ratings}=useResource("ratings",api.getRatings);
  const [difficulty,setDifficulty]=useState<Difficulty>("medium"),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null);
  const selectedDifficulty=queue?.status==="queued"?queue.difficulty??difficulty:difficulty;
  const selected=ratings?.ratings.find(r=>r.difficulty===selectedDifficulty);
  const selectedPopulation=queue?.population?.find(p=>p.difficulty===selectedDifficulty);
  const activeSearchers=Math.max(0,(selectedPopulation?.playersSearching??0)-(queue?.status==="queued"?1:0));
  const waitSeconds=selectedPopulation?.recentMedianWaitSeconds??(activeSearchers>0?60:null);
  const waitLabel=waitSeconds===null?"Waiting for players":waitSeconds<60?"Under 1 min":`About ${Math.ceil(waitSeconds/60)} min`;
  useEffect(()=>{if(queue?.matchId)router.replace(`/match/lobby?matchId=${queue.matchId}`);},[queue?.matchId,router]);
  async function join(){if(busy)return;setBusy(true);setNotice(null);try{const next=await api.joinQueue(difficulty);if(next.matchId)router.push(`/match/lobby?matchId=${next.matchId}`);else refresh();}catch(e){setNotice(e instanceof Error?e.message:"Unable to join.");}finally{setBusy(false);}}
  async function leave(){setBusy(true);try{await api.leaveQueue();refresh();}catch(e){setNotice(e instanceof Error?e.message:"Unable to leave.");}finally{setBusy(false);}}
  return <AppShell><h1 className="text-4xl font-semibold">Choose your arena.</h1><p className="my-4 text-black/60">Complete placements, then match with an opponent in the same difficulty.</p><ErrorNotice message={notice??error}/>
    <div className="my-7 grid gap-4 sm:grid-cols-3">{(["easy","medium","advanced"] as Difficulty[]).map(d=>{const rating=ratings?.ratings.find(r=>r.difficulty===d);return <button key={d} disabled={busy||queue?.status==="queued"} onClick={()=>setDifficulty(d)} className={`rounded-xl border p-6 text-left ${d===difficulty?"border-[#ed5b39] bg-[#fff1ed] ring-2 ring-[#ed5b39]":"border-black/10 bg-white"}`}><div className="flex items-start justify-between gap-3"><span className="text-xl font-bold">{difficultyLabel(d)}</span><span className="shrink-0 text-right text-lg font-bold">{rating?rankLabel(rating.rank):"Unranked"}</span></div><span className="my-3 block text-sm text-black/60">{rating?.placementsCompleted??0}/5 placements</span><span className="mt-2 block text-sm text-black/60">{d==="advanced"?"One round · 20 minutes":`Up to 3 rounds · ${d==="easy"?5:10} minutes each`}</span></button>})}</div>
    {queue?.status==="queued"?<section role="status" className="rounded-xl bg-white p-8"><h2 className="text-2xl font-bold">Finding your opponent<span aria-hidden="true"><span className="queue-dot">.</span><span className="queue-dot">.</span><span className="queue-dot">.</span></span><span className="sr-only">, please wait</span></h2><p className="my-4">Searching the {difficultyLabel(selectedDifficulty)} queue.</p><RankedProgress completed={selected?.placementsCompleted??0} rank={selected?.rank??null} points={selected?.rankProgressPoints??null}/><QueueEstimate waitLabel={waitLabel} players={activeSearchers}/><button disabled={busy} onClick={()=>void leave()} className={buttonClass}>Leave queue</button></section>:<section className="rounded-xl bg-white p-8"><RankedProgress completed={selected?.placementsCompleted??0} rank={selected?.rank??null} points={selected?.rankProgressPoints??null}/><QueueEstimate waitLabel={waitLabel} players={selectedPopulation?.playersSearching??0}/>{selected&&selected.placementsCompleted<5&&process.env.NEXT_PUBLIC_MOCK_API!=="1"?<Link className={buttonClass} href="/onboarding/placement">Complete placements</Link>:<button className={buttonClass} disabled={busy||!queue||!!error} onClick={()=>void join()}>{busy?"Joining…":"Find an opponent"}</button>}</section>}
  </AppShell>;
}

function RankedProgress({completed,rank,points}:{completed:number;rank:{tier:string;division:string|null}|null;points:number|null}){if(completed===5&&rank){const next=nextRank(rank);const currentPoints=Math.min(99,points??0);return <div className="my-5"><p className="mb-3 text-sm text-black/55">Ranked progress</p>{next?<div className="flex items-center gap-2" role="img" aria-label={`${currentPoints} points from ${rankLabel(rank)} toward ${rankLabel(next)}`}><strong className="shrink-0 text-xs sm:text-sm">{rankLabel(rank)}</strong><div className="relative h-9 min-w-0 flex-1"><div className="absolute inset-x-0 top-1/2 h-2 -translate-y-1/2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#ed5b39] transition-[width]" style={{width:`${currentPoints}%`}}/></div><span className="absolute top-1/2 whitespace-nowrap rounded-md bg-[#ed5b39] px-2 py-0.5 text-xs font-bold text-white transition-[left]" style={{left:`${currentPoints}%`,transform:`translate(${currentPoints<8?"0":currentPoints>92?"-100%":"-50%"}, -50%)`}}>{currentPoints} points</span></div><strong className="shrink-0 text-right text-xs sm:text-sm">{rankLabel(next)}</strong></div>:<div className="flex items-center justify-between text-sm font-bold"><span>{rankLabel(rank)}</span><span className="text-black/55">Highest rank</span></div>}</div>;}return <div className="my-5"><div className="mb-2 flex justify-between text-sm"><span>Ranked progress</span><span>{completed}/5 placement matches</span></div><div className="h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[#ed5b39] transition-[width]" style={{width:`${Math.min(5,completed)/5*100}%`}}/></div></div>;}
function QueueEstimate({waitLabel,players}:{waitLabel:string;players:number}){return <div className="mb-5 grid gap-2 text-sm sm:grid-cols-2"><p><span className="text-black/55">Players searching now</span><br/><strong>{players}</strong></p><p><span className="text-black/55">Estimated wait</span><br/><strong>{waitLabel}</strong></p></div>;}
function nextRank(rank:{tier:string;division:string|null}){const divisions=["III","II","I"] as const;const tiers=["Bronze","Silver","Gold","Platinum","Diamond"];if(rank.tier==="Grandmaster Coder")return null;if(rank.tier==="Master Coder")return {tier:"Grandmaster Coder",division:null};const divisionIndex=divisions.indexOf(rank.division as typeof divisions[number]);if(divisionIndex<0)return {tier:rank.tier,division:"III"};if(divisionIndex<2)return {tier:rank.tier,division:divisions[divisionIndex+1]};const tierIndex=tiers.indexOf(rank.tier);return tierIndex===tiers.length-1?{tier:"Master Coder",division:null}:tierIndex<0?null:{tier:tiers[tierIndex+1],division:"III"};}
